export const p = [
  {
    name: "Forex",
    title: "HandsFree Forex Robot(EA)",
    priceM: "100",
    priceY: "1000",
    img: "forex.png",
    nameP: "FOREX",
    namePY: "FOREX_Y",
    paypal: document.getElementById("forex-plan-m").innerHTML,
    paypalY: document.getElementById("forex-plan-y").innerHTML,
    dwnUrl: "Forex HandsFree Robot.ex4",
  },
  {
    name: "Stock",
    title: "HandsFree Stock Robot(EA)",
    priceM: "135",
    priceY: "1350",
    img: "Stock.png",
    nameP: "STOCK",
    namePY: "STOCK_Y",
    paypal: document.getElementById("stock-plan-m").innerHTML,
    paypalY: document.getElementById("stock-plan-y").innerHTML,
    dwnUrl: "Stock HandsFree Robot.ex4",
  },
  {
    name: "Crypto",
    title: "HandsFree Crypto Robot(EA)",
    priceM: "150",
    priceY: "1500",
    img: "crypto.png",
    nameP: "CRYPTO",
    namePY: "CRYPTO_Y",
    paypal: document.getElementById("crypto-plan-m").innerHTML,
    paypalY: document.getElementById("crypto-plan-y").innerHTML,
    dwnUrl: "Crypto HandsFree Robot.ex4",
  },
  {
    name: "Indices",
    title: "HandsFree Indices Robot(EA)",
    priceM: "200",
    priceY: "2000",
    img: "indices.png",
    nameP: "INDICES",
    namePY: "INDICES_Y",
    paypal: document.getElementById("indices-plan-m").innerHTML,
    paypalY: document.getElementById("indices-plan-y").innerHTML,
    dwnUrl: "Indices HandsFree Robot.ex4",
  },
];
