on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: cp ~/.env ./
      # - run: docker-compose up -d --build
      - run: docker stop $(docker ps -a -q --filter="name=magical_bose")
      - run: docker rm $(docker ps -a -q --filter="name=magical_bose")
      - run: docker build -t nidhal/stripe .
      - run: docker run -dp 80:8080 nidhal/stripe
