on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: cp ~/.env ./
      - run: docker rm --force admiring_maxwell
      - run: docker build -t nidhal/stripeexample -f  .
      - run: docker run -dp 80:8080 nidhal/stripeexample
