on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: rm .env
      - run: cp ~/.env ./
      - run: docker --no-cache build -t nidhal/stripe -f nidhal/stripe .
      - run: docker run -dp 80:8080 nidhal/stripe
