on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: cp ~/.env ./
      - run: docker rm $(docker ps -a -q)
      - run: docker build -t nidhal/stripe .
      - run: docker run -dp 80:8080 nidhal/stripe
