on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: cp ~/.env ./
      - run: sudo docker build -t  nidhal/stripeexample .
      - run: sudo docker run -dp 80:8080 nidhal/stripeexample
