on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: cp ~/.env ./
      - run: sudo docker rm --force stripeexample
      - run: sudo docker build --name stripeexample -t nidhal/stripeexample -f nidhal/stripeexample  .
      - run: sudo docker run -dp 80:8080 nidhal/stripeexample
